// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../../../node_modules/bs-platform/lib/es6/curry.js";
import * as Finite from "../node_modules/lambda-streams/lambda_streams/src/Finite.js";

Finite.Sync.pipe(Curry._1(Finite.Sync.make_output, (function (prim) {
            console.log(prim);
            
          })), Finite.Sync.map((function (param) {
            return (param << 1);
          }), Finite.Sync.from_list({
              hd: 1,
              tl: {
                hd: 1,
                tl: {
                  hd: 2,
                  tl: {
                    hd: 3,
                    tl: {
                      hd: 5,
                      tl: {
                        hd: 8,
                        tl: /* [] */0
                      }
                    }
                  }
                }
              }
            })));

export {
  
}
/*  Not a pure module */
